{{- if .Values.helloWorld.enabled -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: a2aregistry-hello-world
  namespace: {{ .Values.httproute.namespace }}
  labels:
    app: a2aregistry-hello-world
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.httproute.gatewayName }}
      namespace: {{ .Values.httproute.namespace }}
  hostnames:
    - {{ .Values.helloWorld.hostname | quote }}
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: a2aregistry-hello-world
          namespace: {{ .Release.Namespace }}
          port: 80
{{- end }}
